# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"

cache:
  paths:
    - .cache/pip
    - .cache/poetry
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - python -m pip install poetry
  - poetry install

test:
  script:
    - poetry run pytest
    - 'poetry run mypy --ignore-missing-imports --allow-untyped-globals *.py'

# https://medium.com/maisonsdumonde/gitlab-ci-cd-and-gitlab-pypi-repository-4916a51d22eb
build_package:
  stage: deploy
  script:
    - pip install twine
    - rm -rf dist/*
    - python setup.py sdist bdist_wheel
    - python -m twine check dist/*
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags
