# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

test:
  script:
    - python tests/test.py
    - 'mypy --ignore-missing-imports --allow-untyped-globals *.py'

# https://medium.com/maisonsdumonde/gitlab-ci-cd-and-gitlab-pypi-repository-4916a51d22eb
build_package:
  stage: deploy
  script:
    - cat $PYPIRC > "$CI_PROJECT_DIR/.pypirc"
    - pip install twine
    - rm -rf dist/*
    - python setup.py bdist_wheel
    - python -m twine check dist/*
    - python -m twine upload --repository gitlab dist/* --config-file "$CI_PROJECT_DIR/.pypirc"
  only:
    - tags
