name: endpoints_coverage

on:
  schedule:
    # Every day
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ./endpoints_coverage.sh

