name: Python package

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.9"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: yes
